### ISSUE TITLE
Fails at login

### ISSUE THREAD

**Issue by brickmack** [ryanfb/sketchfab-dl#5]
I get this error:

Got page title: Log in to your Sketchfab account - Sketchfab
bundler: failed to load command: ./sketchfab-dl.rb (./sketchfab-dl.rb)
Watir::Exception::UnknownObjectException: timed out after 30 seconds, waiting for #<Watir::Button: located: false; {:type=>"submit", :tag_name=>"button"}> to be located
  /home/mack/.bundle/ruby/2.5.0/watir-062ed4522f4a/lib/watir/elements/element.rb:763:in `rescue in element_call'
  /home/mack/.bundle/ruby/2.5.0/watir-062ed4522f4a/lib/watir/elements/element.rb:752:in `element_call'
  /home/mack/.bundle/ruby/2.5.0/watir-062ed4522f4a/lib/watir/elements/element.rb:129:in `click'
  /home/mack/Downloads/sketchfab-dl-master/sketchfab-dl.rb:30:in `login'
  /home/mack/Downloads/sketchfab-dl-master/sketchfab-dl.rb:157:in `<top (required)>'

on ubuntu 18.04

**Comment by ryanfb** [comment]
Should be fixed now. Thanks for the report!
